name: trainer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.2
  google_fonts: ^6.3.2
  http: ^1.6.0
  image_picker: ^1.2.1
  provider: ^6.1.5+1
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
